apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/creatorId: user-gpcv5
  labels:
    cattle.io/creator: norman
  name: artemis-app
spec:
  rules:
  - host: artemis-app.artemis.rancher.localhost
    http:
      paths:
      - backend:
          service:
            name: artemis-app
            port:
              number: 8080
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - artemis-app.artemis.rancher.localhost
